version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - ../uploads:/app/uploads
      - ../outputs:/app/outputs
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - calibre

  frontend:
    build:
      context: ../frontend/web
      dockerfile: ../../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ../uploads:/config/uploads
      - ../outputs:/config/outputs
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  node_modules: